version: '3.3'

services:
  devtools:
    image: python:3.10
    hostname: devtools
    command: sh -c "pip3 install -r requirements.txt && waitress-serve --port=2718 --call app:create_app"
    working_dir: /dist
    volumes:
      - ./:/dist
    environment:
      - DB_HOST=...
      - DB_USER=...
      - DB_PASS=...
      - DB_NAME=...
