name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t devtools .

      - name: Stop Docker container
        run: |
          docker stop devtools || true

      - name: Remove Docker container
        run: |
          docker rm devtools || true

      - name: Run Docker container
        run: |
          docker run -d \
            --name devtools \
            --network stack_default \
            -p "8100:2718" \
            -e DB_HOST=172.18.0.8 \
            -e DB_USER=${DB_USER} \
            -e DB_PASS=${DB_PASS} \
            -e DB_NAME=${DB_NAME} \
            devtools
